[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "MaskAD"
version = "0.1.0"
description = "MaskAD Autonomous Driving Planner"
authors = [{name = "Tianle"}]
dependencies = []

[tool.setuptools.packages.find]
where = ["."]
